// MCPForge — root ESLint flat config.
// Covers the whole TS/JS surface of the repo. See CLAUDE.md §5 (code style)
// and 02_TECHNICAL_ARCHITECTURE.md §10.2 for the driver-isolation rule below.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';
// W0-A3 — the four guard rules, loaded from the local workspace plugin.
import mcpforge from './tools/eslint-rules/src/index.js';

// 02 §10.2: both SQLite and Postgres drivers sit under the repository
// interface. No application code may import either directly — only
// core/gateway/store/** may reach them. This rule is the enforcement,
// alongside the no-service-account-fallback guard rule (W0-A3).
const driverIsolation = {
  paths: [
    {
      name: 'better-sqlite3',
      message:
        'better-sqlite3 may only be imported inside core/gateway/store/** — reach the store through the repository interface (02 §10.2).',
    },
    {
      name: 'pg',
      message:
        'pg may only be imported inside core/gateway/store/** — reach the store through the repository interface (02 §10.2).',
    },
  ],
};

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      '**/.next/**',
      '**/*.tsbuildinfo',
      'generated/**',
      'adapters/oracle-worker/**', // Python (uv) — never ESLint's concern.
      '.forge-build/**',
      '.mcpforge/**',
      // Next.js-generated, "should not be edited" per its own header
      // comment — regenerated by `next dev`/`next build` on every run.
      'core/portal/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    plugins: { mcpforge },
    rules: {
      'no-restricted-imports': ['error', driverIsolation],
      // W0-A3 guard rules — the security and design non-negotiables, live
      // across the whole repo. CLAUDE.md §2 items 1 and 8; 03 §13.6.
      'mcpforge/no-service-account-fallback': 'error',
      'mcpforge/no-secret-value-escape': 'error',
      'mcpforge/no-raw-color': 'error',
      'mcpforge/no-retired-brand-strings': 'error',
    },
  },
  {
    // The guard rules' own test fixtures are crafted violations by design —
    // they exist as strings inside the RuleTester cases, not as real code.
    files: ['tools/eslint-rules/test/**'],
    rules: {
      'mcpforge/no-service-account-fallback': 'off',
      'mcpforge/no-secret-value-escape': 'off',
      'mcpforge/no-raw-color': 'off',
      'mcpforge/no-retired-brand-strings': 'off',
    },
  },
  {
    // core/portal/src/design/tokens.ts is GENERATED by build-tokens.ts from
    // tokens.semantic.css (03 §13.4) — it is the typed mirror of the colour
    // system, not a component restating a colour of its own invention. The
    // doc's own §13.4 example shows it holding literal hex. contrast.test.ts
    // is the §12.1 gate and W0-J1 requires it to pin the exact literal
    // values 03 §4.6/§13.2 name (light --text-3 `#6E7379`, etc.) so a future
    // edit cannot silently reintroduce a marginal or wrong one. Both are the
    // same shape of exception `tokens.primitives.css` already gets, just for
    // the generated JS mirror and its test rather than the source CSS.
    files: [
      'core/portal/src/design/tokens.ts',
      'core/portal/src/design/contrast.test.ts',
    ],
    rules: {
      'mcpforge/no-raw-color': 'off',
    },
  },
  {
    // The rules themselves must name the patterns they forbid.
    files: ['tools/eslint-rules/src/**'],
    rules: {
      'mcpforge/no-service-account-fallback': 'off',
      'mcpforge/no-retired-brand-strings': 'off',
      'mcpforge/no-raw-color': 'off',
    },
  },
  {
    // W0-N5 — the SecretStore seam itself. This is the module that implements
    // get() and defines revealSecretValue(); it is where a secret value
    // necessarily exists at all, so the rule that keeps values from ESCAPING it
    // cannot also apply inside it. Narrow and visible on purpose: CLAUDE.md #8
    // still names exactly two CONSUMING trees (adapters/** and
    // core/gateway/identity/**), the rule's own allowed-path helper is
    // unchanged, and core/gateway/secrets/boundary.test.ts asserts the
    // boundary structurally — from outside the linter, where an
    // eslint-disable cannot reach it.
    files: ['core/gateway/secrets/**/*.ts'],
    rules: {
      'mcpforge/no-secret-value-escape': 'off',
    },
  },
  {
    // The one place the drivers are allowed: the repository interface itself.
    files: ['core/gateway/store/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
);
