import { loadCatalogueIndex } from '@mcpforge/registry/index/server';
import { cpSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';
import { manifestSha256 } from './hash.js';
import { runCodegen } from './pipeline.js';
import { provenanceCommentHeader, provenanceJsonFields } from './provenance.js';
import { codegenVersion } from './version.js';
import { readGeneratedFile, serializeJsonDeterministic, sortKeysDeep } from './writer.js';

const here = dirname(fileURLToPath(import.meta.url));
const fixturesRepoRoot = join(here, 'fixtures');
const fixtureManifestPath = join(
  fixturesRepoRoot,
  'manifests',
  'jde',
  'fin',
  'ap',
  'voucher.create.tool.yaml',
);

const tmpDirs: string[] = [];

/** A throwaway repo root: fixture manifests copied in, so each test gets an isolated `generated/`. */
function freshRepoRoot(): string {
  const dir = mkdtempSync(join(tmpdir(), 'mcpforge-emit-'));
  tmpDirs.push(dir);
  // Copy the fixture manifest tree in.
  cpSync(join(fixturesRepoRoot, 'manifests'), join(dir, 'manifests'), { recursive: true });
  // W0-B8: role scopes are compiled from `roles/<id>.yaml`, not from each
  // tool's `coreForRoles`, so the fixture's roles/ tree must come across too.
  cpSync(join(fixturesRepoRoot, 'roles'), join(dir, 'roles'), { recursive: true });
  return dir;
}

afterEach(() => {
  while (tmpDirs.length > 0) {
    const dir = tmpDirs.pop()!;
    rmSync(dir, { recursive: true, force: true });
  }
});

describe('manifestSha256', () => {
  it('is a stable, deterministic hex sha256 of exact source content', () => {
    const a = manifestSha256('hello');
    const b = manifestSha256('hello');
    const c = manifestSha256('hello!');
    expect(a).toBe(b);
    expect(a).not.toBe(c);
    expect(a).toMatch(/^[0-9a-f]{64}$/);
  });
});

describe('provenance header — 02 §2.3 exact format', () => {
  it('the comment header is exactly the two documented lines', () => {
    const header = provenanceCommentHeader({
      manifestPath: 'manifests/jde/fin/ap/voucher.create.tool.yaml',
      manifestSha256: '7f3c000000000000000000000000000000000000000000000000000000000',
      codegenVersion: '1.4.2',
    });
    const lines = header.split('\n');
    expect(lines).toHaveLength(2);
    expect(lines[0]).toBe(
      '// GENERATED BY forge codegen FROM manifests/jde/fin/ap/voucher.create.tool.yaml',
    );
    expect(lines[1]).toBe(
      '// manifest-sha256: 7f3c000000000000000000000000000000000000000000000000000000000  codegen-version: 1.4.2   DO NOT EDIT',
    );
  });

  it('every generated placeholder carries the JSON provenance fields with the same two lines', () => {
    const fields = provenanceJsonFields({
      manifestPath: 'manifests/x.tool.yaml',
      manifestSha256: 'abc123',
      codegenVersion: '9.9.9',
    });
    expect(fields['//1']).toBe('GENERATED BY forge codegen FROM manifests/x.tool.yaml');
    expect(fields['//2']).toBe('manifest-sha256: abc123  codegen-version: 9.9.9   DO NOT EDIT');
  });
});

describe('sortKeysDeep', () => {
  it('sorts object keys at every depth, leaves array order untouched', () => {
    const input = { b: 1, a: { d: 2, c: 3 }, z: [{ y: 1, x: 2 }] };
    const sorted = sortKeysDeep(input) as Record<string, unknown>;
    expect(Object.keys(sorted)).toEqual(['a', 'b', 'z']);
    expect(Object.keys(sorted['a'] as object)).toEqual(['c', 'd']);
    // Array element order preserved; only the object *inside* is key-sorted.
    expect(Object.keys((sorted['z'] as unknown[])[0] as object)).toEqual(['x', 'y']);
  });
});

describe('serializeJsonDeterministic', () => {
  it('produces byte-identical output for the same value across repeated calls', async () => {
    const value = { b: 1, a: 2, nested: { z: 1, a: 2 } };
    const first = await serializeJsonDeterministic(value, fixturesRepoRoot);
    const second = await serializeJsonDeterministic(value, fixturesRepoRoot);
    expect(first).toBe(second);
    expect(first.endsWith('\n')).toBe(true);
  });
});

describe('codegenVersion', () => {
  it('reads a non-empty semver-shaped string from the codegen package.json', () => {
    const v = codegenVersion();
    expect(typeof v).toBe('string');
    expect(v.length).toBeGreaterThan(0);
  });
});

describe('runCodegen — end-to-end pipeline', () => {
  it('processes the fixture manifest and writes the real per-tool artefact set (W0-B6)', async () => {
    const repoRoot = freshRepoRoot();
    const report = await runCodegen(repoRoot);

    expect(report.ok).toBe(true);
    expect(report.manifestsProcessed).toBe(1);
    expect(report.filesWritten).toEqual([
      'generated/cards/jde.ap.voucher.create.json',
      'generated/docs/tools/jde.ap.voucher.create.md',
      'generated/index/catalogue-index.json',
      'generated/roles/p2p.scope.json',
      'generated/tools/jde.ap.voucher.create/contract.test.ts',
      'generated/tools/jde.ap.voucher.create/handler.generated.ts',
      'generated/tools/jde.ap.voucher.create/schema.json',
      'generated/tools/jde.ap.voucher.create/tool.ts',
      'generated/tools/jde.ap.voucher.create/unit.test.ts',
    ]);

    const written = readGeneratedFile(
      join(repoRoot, 'generated', 'tools', 'jde.ap.voucher.create', 'schema.json'),
    );
    const parsed = JSON.parse(written) as Record<string, unknown>;
    expect(parsed['title']).toBe('jde.ap.voucher.create input');

    const rawManifestSource = readFileSync(join(repoRoot, 'manifests/jde/fin/ap/voucher.create.tool.yaml'), 'utf8');
    const expectedHash = manifestSha256(rawManifestSource);
    expect(parsed['//2']).toBe(
      `manifest-sha256: ${expectedHash}  codegen-version: ${codegenVersion()}   DO NOT EDIT`,
    );
    expect(parsed['//1']).toBe(
      'GENERATED BY forge codegen FROM manifests/jde/fin/ap/voucher.create.tool.yaml',
    );
  });

  it('DONE CRITERION (a): running codegen twice on an unchanged tree is byte-identical', async () => {
    const repoRoot = freshRepoRoot();
    const first = await runCodegen(repoRoot);
    const firstBytes = readGeneratedFile(join(repoRoot, ...first.filesWritten[0]!.split('/')));

    const second = await runCodegen(repoRoot);
    const secondBytes = readGeneratedFile(join(repoRoot, ...second.filesWritten[0]!.split('/')));

    expect(first).toEqual(second);
    expect(secondBytes).toBe(firstBytes);
  });

  it('DONE CRITERION (c): deleting generated/ and regenerating reproduces it byte-identically', async () => {
    const repoRoot = freshRepoRoot();
    const first = await runCodegen(repoRoot);
    const firstBytes = readGeneratedFile(join(repoRoot, ...first.filesWritten[0]!.split('/')));

    rmSync(join(repoRoot, 'generated'), { recursive: true, force: true });

    const second = await runCodegen(repoRoot);
    const secondBytes = readGeneratedFile(join(repoRoot, ...second.filesWritten[0]!.split('/')));

    expect(second).toEqual(first);
    expect(secondBytes).toBe(firstBytes);
  });

  it('an empty manifest tree processes zero manifests and writes zero files', async () => {
    const emptyRoot = mkdtempSync(join(tmpdir(), 'mcpforge-emit-empty-'));
    tmpDirs.push(emptyRoot);
    const report = await runCodegen(emptyRoot);
    expect(report).toEqual({
      ok: true,
      manifestsProcessed: 0,
      // W0-G1: `generated/index/catalogue-index.json` is still written — an
      // empty catalogue is a real, deterministic artefact, not a skipped one.
      filesWritten: ['generated/index/catalogue-index.json'],
      contractDrift: [],
      customBindingsCreated: [],
    });
  });
});

// W0-G1 — the catalogue index build artefact, wired into `forge codegen`'s
// pipeline (02 §5.4.1). `@mcpforge/registry/index` owns the shape and the
// leak-guard logic (see core/registry/src/index/build.test.ts for those
// unit tests); this describes only proves the WIRING: the pipeline actually
// calls it, actually writes it, and actually feeds it real manifest data.
describe('runCodegen — the catalogue index artefact (W0-G1)', () => {
  it('writes generated/index/catalogue-index.json, loadable back through @mcpforge/registry/index, carrying the fixture tool with its filters, lexical document and disambiguation text', async () => {
    const repoRoot = freshRepoRoot();
    const report = await runCodegen(repoRoot);
    expect(report.ok).toBe(true);
    expect(report.filesWritten).toContain('generated/index/catalogue-index.json');

    const index = loadCatalogueIndex(repoRoot);
    expect(index.tools).toHaveLength(1);
    const entry = index.tools[0]!;
    expect(entry.id).toBe('jde.ap.voucher.create');
    expect(entry.filters).toEqual({
      app: 'jde',
      module: 'ap',
      entity: 'voucher',
      verb: 'create',
      bindingType: 'function',
      archetype: 'transactional',
      sensitivity: 'financial',
      write: true,
      processTags: ['P2P'],
      packageTags: [],
      roles: ['p2p'],
      status: 'unresolved',
    });
    expect(entry.disambiguation).toContain('Creates a NEW voucher');
    for (const expected of [
      'Create a voucher',
      'supplier invoice',
      'book a payable',
      'voucher',
      'Accounts Payable',
      'jde',
      'ap',
      'create',
    ]) {
      expect(entry.lexicalDocument).toContain(expected);
    }
  });

  it('the raw file carries the //1 / //2 provenance pseudo-comment fields, same convention as every other generated JSON artefact', async () => {
    const repoRoot = freshRepoRoot();
    await runCodegen(repoRoot);
    const raw = readGeneratedFile(join(repoRoot, 'generated', 'index', 'catalogue-index.json'));
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    expect(typeof parsed['//1']).toBe('string');
    expect(parsed['//1']).toContain('GENERATED BY forge codegen');
    expect(typeof parsed['//2']).toBe('string');
    expect(parsed['//2']).toContain('DO NOT EDIT');
  });

  it('an empty manifest tree still emits a valid, empty catalogue index', async () => {
    const emptyRoot = mkdtempSync(join(tmpdir(), 'mcpforge-emit-empty-index-'));
    tmpDirs.push(emptyRoot);
    await runCodegen(emptyRoot);
    const index = loadCatalogueIndex(emptyRoot);
    expect(index.tools).toEqual([]);
  });

  it('DONE CRITERION: the evals/** leak rule (W0-B3) is exercised here — a benchmark intent copied verbatim into an alias fails the codegen run, and no catalogue-index.json is left on disk from a prior good run when it does', async () => {
    const repoRoot = freshRepoRoot();
    // A clean run first, to prove the leak guard applies even when a valid
    // artefact already exists on disk (the guard fires every run, not only
    // on first write).
    await runCodegen(repoRoot);

    // Plant a benchmark intent, verbatim, as an alias — the exact scenario
    // `policy.eval-alias-leak` (core/codegen/src/rules/evals.ts) exists for.
    mkdirSync(join(repoRoot, 'evals', 'jde-fin-ap'), { recursive: true });
    writeFileSync(
      join(repoRoot, 'evals', 'jde-fin-ap', 'intents.yaml'),
      'intents:\n  - text: book a payable\n',
      'utf8',
    );
    const manifestPath = join(repoRoot, 'manifests', 'jde', 'fin', 'ap', 'voucher.create.tool.yaml');
    const original = readFileSync(manifestPath, 'utf8');
    // The fixture's aliases already include "book a payable" verbatim
    // (core/codegen/src/emit/fixtures/manifests/jde/fin/ap/voucher.create.tool.yaml)
    // — no manifest edit needed to create the collision.
    expect(original).toContain('book a payable');

    await expect(runCodegen(repoRoot)).rejects.toThrow(/benchmark intent/i);
  });
});

// Sanity: the fixture manifest file itself exists where the tests expect it.
describe('fixture manifest', () => {
  it('is present and non-empty', () => {
    const content = readFileSync(fixtureManifestPath, 'utf8');
    expect(content.length).toBeGreaterThan(0);
  });
});
