// MCPForge — the provenance-header builder. W0-B4.
//
// 02 §2.3's exact, worked format (a comment-capable file, e.g. `.ts`):
//
//   // GENERATED BY forge codegen FROM manifests/jde/fin/ap/voucher.create.tool.yaml
//   // manifest-sha256: 7f3c…  codegen-version: 1.4.2   DO NOT EDIT
//
// This module builds exactly that string, byte for byte, plus a documented
// fallback for file types that cannot carry a `//` comment at all (JSON).
// 02 is silent on the JSON case — every generated artefact table in §2.3
// that is JSON (`schema.json`, discovery cards, the catalogue index) still
// needs *some* provenance, and W0-B6 will be the task that actually emits
// those files, but the convention has to exist here, in the shared emit
// engine, so every future JSON emitter uses the same one rather than each
// inventing its own.

export interface ProvenanceInfo {
  /** Repo-relative, forward-slash path to the source manifest, e.g. `manifests/jde/fin/ap/voucher.create.tool.yaml`. */
  readonly manifestPath: string;
  /** Lower-case hex sha256 of the manifest's raw source content (`manifestSha256`). */
  readonly manifestSha256: string;
  /** The codegen package's own version (`codegenVersion()`). */
  readonly codegenVersion: string;
}

/** Line 1 of the header, identical for every file type: what generated this file, from what. */
export function provenanceLine1(info: ProvenanceInfo): string {
  return `GENERATED BY forge codegen FROM ${info.manifestPath}`;
}

/** Line 2 of the header, identical for every file type: the hash, the tool version, the warning. */
export function provenanceLine2(info: ProvenanceInfo): string {
  return `manifest-sha256: ${info.manifestSha256}  codegen-version: ${info.codegenVersion}   DO NOT EDIT`;
}

/**
 * The exact two-line `//`-comment header from 02 §2.3, for any file type
 * whose grammar supports a leading line comment (`.ts`, `.js`, `.md` via
 * HTML comments is NOT this — see `provenanceHtmlComment` below if that's
 * ever needed).
 *
 * NOTE ON "three-line" (TASKS.md W0-B4's `done:` wording) vs. "two-line" (02
 * §2.3's actual worked example): 02 §2.3 shows exactly two `//` lines, no
 * more. This function reproduces 02 §2.3 verbatim, since CLAUDE.md §1 makes
 * the numbered documents authoritative over TASKS.md's prose paraphrase of
 * them. JUDGMENT CALL, documented rather than blocking: if "three-line" was
 * meant literally, the third line is not specified anywhere and is not
 * invented here.
 */
export function provenanceCommentHeader(info: ProvenanceInfo): string {
  return `// ${provenanceLine1(info)}\n// ${provenanceLine2(info)}`;
}

/**
 * JSON has no comment syntax. JUDGMENT CALL (02 is silent on this;
 * documented here rather than blocked): reserved `"//..."` keys are a
 * widely-recognised JSON "pseudo-comment" convention (tolerated by parsers
 * because a JSON key can be any string) and are used by other tools (e.g.
 * `tsconfig.json` authors commonly rely on the same trick). Two reserved
 * keys, carrying exactly the two 02 §2.3 lines as values, sorted so they
 * land first under the deterministic-writer's key-sort (both start with the
 * ASCII `/` character, 0x2F, which sorts before every alphanumeric key any
 * real generated artefact will use).
 */
export function provenanceJsonFields(info: ProvenanceInfo): Readonly<Record<string, string>> {
  return {
    '//1': provenanceLine1(info),
    '//2': provenanceLine2(info),
  };
}
