// MCPForge — W0-N12: proof that the Consumers tab's right pane is a REAL compile.
//
// The failure mode this task exists to prevent (03 §16.2) is a consumer editor
// that shows an authorization which is not the one the record actually grants.
// A test asserting against a hand-written expected object would not catch that
// — it would only prove the mock and the expectation agree. So every assertion
// below cross-checks the portal's answer against one of:
//   (a) a DIRECT call to `compileConsumerAuthorization` — the real W0-B8/W0-N4
//       compiler function — on the same edited record, or
//   (b) the real `scaffoldConsumerRecord` / `consumerRecordSchema` (what
//       `forge consumer new` produces and what `forge validate` accepts), or
//   (c) the real `resolveStandingAuthorization`, through an approval record
//       written into the sandbox's own `approvals/` and read back out of the
//       compiled artefact.
import { describe, expect, it } from 'vitest';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import { compileConsumerAuthorization, readConsumer } from '@mcpforge/codegen/compile';
import {
  renderConsumerRecord,
  scaffoldConsumerRecord,
  type ConsumerRecord,
} from '@mcpforge/gateway/consumer';

import { compileConsumerDraft } from './compile-consumer';

const TODAY = '2026-09-10';
const ID = 'w0n12-test-consumer';

/** The same scaffold `forge consumer new` writes. Nobody hand-builds a record here. */
function baseRecord(): ConsumerRecord {
  return scaffoldConsumerRecord({
    id: ID,
    consumerClass: 'autonomous-agent',
    label: 'W0-N12 test consumer',
    owner: 'oracle-ai-practice',
    steward: 'test.steward',
    humanInTheLoop: false,
    today: TODAY,
  });
}

function yamlFor(record: Record<string, unknown>): string {
  return renderConsumerRecord(record as ConsumerRecord);
}

/** The same record, run through the REAL compiler directly, for cross-checking. */
function directCompile(yamlText: string): Record<string, unknown> {
  const doc = parseYaml(yamlText) as Record<string, unknown>;
  const view = readConsumer({
    id: String(doc['id']),
    doc,
    // `readConsumer` reads only `id` and `doc`; the file descriptor is unused.
    file: { file: `consumers/${ID}.consumer.yaml`, absPath: '', dir: 'consumers' },
  } as unknown as Parameters<typeof readConsumer>[0]);
  return compileConsumerAuthorization(
    view,
    { manifestPath: '', manifestSha256: '', codegenVersion: '' },
    TODAY,
  ).artefact;
}

/** Drop provenance so the comparison is about the AUTHORIZATION, not the hashes. */
function authorizationOnly(artefact: Record<string, unknown>): Record<string, unknown> {
  const copy = { ...artefact };
  for (const key of Object.keys(copy)) {
    // `provenanceJsonFields` emits its "GENERATED BY forge codegen FROM …"
    // banner as `//1` / `//2`, carrying the manifest path and sha — which
    // differ by construction between a sandbox file and a direct in-memory
    // call, and say nothing about what the consumer may reach.
    if (key.startsWith('//') || key.startsWith('_')) delete copy[key];
  }
  return copy;
}

describe('compileConsumerDraft — the live compile is the real compiler', () => {
  it('compiles a scaffolded registration and agrees field-for-field with a DIRECT compiler call', async () => {
    const yamlText = yamlFor(baseRecord());
    const draft = await compileConsumerDraft(ID, yamlText, '', TODAY);
    expect(draft.error).toBeUndefined();

    // (a) — the portal's rendered values against the real compiler's artefact.
    const direct = directCompile(yamlText);
    const parsed = JSON.parse(draft.artefactJson) as Record<string, unknown>;
    expect(authorizationOnly(parsed)).toEqual(authorizationOnly(direct));

    // And the closed scaffold really is closed — nothing granted by default.
    expect(draft.bindingTypes).toEqual([]);
    expect(draft.roles).toEqual([]);
    expect(draft.packages).toEqual([]);
    expect(draft.writeAllowed).toBe(false);
    expect(draft.maxSensitivity).toBe('public');
    expect(draft.effectiveStatus).toBe('active');
    expect(draft.humanInTheLoop).toBe(false);
    expect(draft.grants).toEqual([]);
  }, 180_000);

  it('WIDENING the record widens the compiled artefact, and the delta is visible', async () => {
    const record = baseRecord();
    const widened = yamlFor({
      ...record,
      authorizations: {
        ...record.authorizations,
        bindingTypes: ['rest', 'plsql'],
        maxSensitivity: 'financial',
        writeAllowed: true,
        roles: ['p2p'],
      },
    });
    const mergedJson = (await compileConsumerDraft(ID, yamlFor(record), '', TODAY)).artefactJson;
    const draft = await compileConsumerDraft(ID, widened, mergedJson, TODAY);
    expect(draft.error).toBeUndefined();

    const direct = directCompile(widened);
    expect(authorizationOnly(JSON.parse(draft.artefactJson) as Record<string, unknown>)).toEqual(
      authorizationOnly(direct),
    );

    // 02 §11.2's whole reason for compiling a consumer: the widening is a diff.
    const bindingTypes = draft.listDeltas.find((d) => d.field === 'bindingTypes')!;
    // The scaffold granted no binding type at all, so BOTH are additions.
    expect(bindingTypes.added).toEqual(['plsql', 'rest']);
    expect(draft.listDeltas.find((d) => d.field === 'roles')!.added).toEqual(['p2p']);
    const scalars = draft.scalarDeltas.map((d) => d.field);
    expect(scalars).toContain('writeAllowed');
    expect(scalars).toContain('maxSensitivity');
  }, 180_000);

  it('an expired REGISTRATION compiles to effectiveStatus: expired, not to what status: claims', async () => {
    const record = baseRecord();
    const stale = yamlFor({ ...record, expiresAt: '2026-01-01' });
    const draft = await compileConsumerDraft(ID, stale, '', TODAY);
    expect(draft.error).toBeUndefined();
    expect(draft.status).toBe('active');
    // `today` is the real clock inside codegen, and 2026-01-01 is behind every
    // clock this test can run under.
    expect(draft.expired).toBe(true);
    expect(draft.effectiveStatus).toBe('expired');
  }, 180_000);

  it('a bindingGrant compiles with its approver and expiry, and an EXPIRED one is shown, not dropped', async () => {
    const record = baseRecord();
    const withGrants = yamlFor({
      ...record,
      authorizations: { ...record.authorizations, bindingTypes: ['plsql'] },
      bindingGrants: [
        {
          bindingType: 'plsql',
          names: ['MCPFORGE_WRAP.AP_VOUCHER'],
          approvalRef: 'APR-W0N12-LIVE',
          approver: 'named.approver',
          expiresAt: '2099-01-01',
        },
        {
          bindingType: 'function',
          names: ['AP_ORCH_FAMILY'],
          approvalRef: 'APR-W0N12-DEAD',
          approver: 'named.approver',
          expiresAt: '2020-01-01',
        },
      ],
    });
    const draft = await compileConsumerDraft(ID, withGrants, '', TODAY);
    expect(draft.error).toBeUndefined();

    const direct = directCompile(withGrants);
    expect(authorizationOnly(JSON.parse(draft.artefactJson) as Record<string, unknown>)).toEqual(
      authorizationOnly(direct),
    );

    expect(draft.grants).toHaveLength(2);
    const live = draft.grants.find((g) => g.approvalRef === 'APR-W0N12-LIVE')!;
    const dead = draft.grants.find((g) => g.approvalRef === 'APR-W0N12-DEAD')!;
    expect(live.approver).toBe('named.approver');
    expect(live.names).toEqual(['MCPFORGE_WRAP.AP_VOUCHER']);
    expect(live.expired).toBe(false);
    expect(live.expiry.token).toBe('status-ok');
    // Visibility of a dead grant is the whole point (compileGrant's own words).
    expect(dead.expired).toBe(true);
    expect(dead.expiry.token).toBe('status-danger');
  }, 180_000);

  it('an expiry inside 30 days is chipped --status-write off the REAL compiled grant', async () => {
    const record = baseRecord();
    // 20 days from the pinned `today`. The compiler calls it live; the 30-day
    // presentation threshold is what turns it amber.
    const soon = yamlFor({
      ...record,
      authorizations: { ...record.authorizations, bindingTypes: ['plsql'] },
      bindingGrants: [
        {
          bindingType: 'plsql',
          names: ['MCPFORGE_WRAP.AP_VOUCHER'],
          approvalRef: 'APR-W0N12-SOON',
          approver: 'named.approver',
          expiresAt: '2026-09-30',
        },
      ],
    });
    const draft = await compileConsumerDraft(ID, soon, '', TODAY);
    expect(draft.error).toBeUndefined();
    const grant = draft.grants[0]!;
    expect(grant.expiresAt).toBe('2026-09-30');
    expect(grant.expiry.state).toBe('expiring');
    expect(grant.expiry.token).toBe('status-write');
    expect(grant.expiry.daysRemaining).toBe(20);
  }, 180_000);

  it('an UNRESOLVABLE standingAuthorization compiles to its failing status, never to "active"', async () => {
    const record = baseRecord();
    const withStanding = yamlFor({
      ...record,
      authorizations: { ...record.authorizations, bindingTypes: ['plsql'] },
      bindingGrants: [
        {
          bindingType: 'plsql',
          names: ['MCPFORGE_WRAP.AP_VOUCHER'],
          approvalRef: 'APR-W0N12-LIVE',
          approver: 'named.approver',
          expiresAt: '2099-01-01',
          // `approvals/` holds no such record in this repository.
          standingAuthorization: 'APR-W0N12-NO-SUCH-RECORD',
        },
      ],
    });
    const draft = await compileConsumerDraft(ID, withStanding, '', TODAY);
    expect(draft.error).toBeUndefined();

    // (c) — the real `resolveStandingAuthorization`, fail-closed.
    const standing = draft.grants[0]!.standing!;
    expect(standing.ref).toBe('APR-W0N12-NO-SUCH-RECORD');
    expect(standing.status).toBe('unresolved');
    expect(standing.effective).toBe(false);
    expect(standing.approver).toBe('');
    expect(standing.expiry.token).toBe('status-danger');

    const direct = directCompile(withStanding);
    expect(authorizationOnly(JSON.parse(draft.artefactJson) as Record<string, unknown>)).toEqual(
      authorizationOnly(direct),
    );
  }, 180_000);

  it('a record that cannot compile reports an error with an actionable next, and NO stale authorization', async () => {
    const draft = await compileConsumerDraft(ID, ': not : valid : yaml :\n  - [', '', TODAY);
    expect(draft.error).toBeDefined();
    expect(draft.error!.next.trim()).not.toBe('');
    expect(draft.error!.next.toLowerCase()).not.toContain('try again');
    expect(draft.artefactJson).toBe('');
    expect(draft.bindingTypes).toEqual([]);
    expect(draft.grants).toEqual([]);
  }, 180_000);

  it('a record whose kind is not Consumer produces no artefact and says so', async () => {
    const record = baseRecord();
    const wrongKind = stringifyYaml({ ...record, kind: 'Role' });
    const draft = await compileConsumerDraft(ID, wrongKind, '', TODAY);
    expect(draft.error).toBeDefined();
    expect(draft.error!.message).toContain(ID);
    expect(draft.artefactJson).toBe('');
  }, 180_000);
});
