import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { buildCatalogueIndex } from './build.js';
import { CatalogueIndexLoadError, loadCatalogueIndex } from './load.js';
import type { CatalogueIndexToolInput } from './types.js';

const tmpDirs: string[] = [];

function freshRepoRoot(): string {
  const dir = mkdtempSync(join(tmpdir(), 'mcpforge-registry-index-'));
  tmpDirs.push(dir);
  return dir;
}

function writeIndexFile(repoRoot: string, content: unknown): void {
  const dir = join(repoRoot, 'generated', 'index');
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'catalogue-index.json'), JSON.stringify(content), 'utf8');
}

const sampleTool: CatalogueIndexToolInput = {
  id: 'jde.ap.voucher.create',
  title: 'Create a voucher',
  purpose: 'Create an AP voucher against a supplier.',
  aliases: ['supplier invoice'],
  disambiguation: 'Creates a NEW voucher.',
  entity: 'voucher',
  verb: 'create',
  app: 'jde',
  module: 'ap',
  appLabel: 'jde',
  moduleLabel: 'JD Edwards Financials — Accounts Payable',
  functionalArea: 'Accounts Payable',
  bindingType: 'function',
  archetype: 'transactional',
  sensitivity: 'financial',
  write: true,
  processTags: ['P2P'],
  packageTags: ['jde-fin'],
  roles: ['p2p'],
  status: 'unresolved',
};

afterEach(() => {
  while (tmpDirs.length > 0) {
    rmSync(tmpDirs.pop()!, { recursive: true, force: true });
  }
});

describe('loadCatalogueIndex', () => {
  it('loads back exactly what buildCatalogueIndex produced, round-tripped through JSON', () => {
    const built = buildCatalogueIndex([sampleTool], new Set());
    const repoRoot = freshRepoRoot();
    writeIndexFile(repoRoot, built);

    const loaded = loadCatalogueIndex(repoRoot);
    expect(loaded).toEqual(built);
  });

  it('loads back correctly even with provenance pseudo-comment fields alongside "tools" (the shape codegen actually writes)', () => {
    const built = buildCatalogueIndex([sampleTool], new Set());
    const repoRoot = freshRepoRoot();
    writeIndexFile(repoRoot, {
      '//1': 'GENERATED BY forge codegen FROM manifests/**/*.tool.yaml',
      '//2': 'manifest-sha256: abc  codegen-version: 0.0.0   DO NOT EDIT',
      ...built,
    });

    const loaded = loadCatalogueIndex(repoRoot);
    expect(loaded).toEqual(built);
  });

  it('throws CatalogueIndexLoadError, actionably, when the file is absent (fresh checkout, codegen not yet run)', () => {
    const repoRoot = freshRepoRoot();
    expect(() => loadCatalogueIndex(repoRoot)).toThrow(CatalogueIndexLoadError);
    expect(() => loadCatalogueIndex(repoRoot)).toThrow(/forge codegen/);
  });

  it('throws CatalogueIndexLoadError on invalid JSON rather than returning a partial index', () => {
    const repoRoot = freshRepoRoot();
    mkdirSync(join(repoRoot, 'generated', 'index'), { recursive: true });
    writeFileSync(join(repoRoot, 'generated', 'index', 'catalogue-index.json'), '{ not json', 'utf8');
    expect(() => loadCatalogueIndex(repoRoot)).toThrow(CatalogueIndexLoadError);
  });

  it('throws CatalogueIndexLoadError when "tools" is missing', () => {
    const repoRoot = freshRepoRoot();
    writeIndexFile(repoRoot, { notTools: [] });
    expect(() => loadCatalogueIndex(repoRoot)).toThrow(/"tools" array is missing/);
  });

  it('throws CatalogueIndexLoadError when an entry is missing a required filter field', () => {
    const repoRoot = freshRepoRoot();
    writeIndexFile(repoRoot, {
      tools: [{ id: 'x', lexicalDocument: 'x', disambiguation: null, filters: { app: 'jde' } }],
    });
    expect(() => loadCatalogueIndex(repoRoot)).toThrow(/filters\./);
  });
});
